export default [
  { nick: "agbc", full: "asiangirlsbeingcute" },
  { nick: "atbge", full: "atbge" },
  { nick: "bf", full: "bossfight" },
  { nick: "bmf", full: "blackmagicfuckery" },
  { nick: "cc", full: "cursedcomments" },
  { nick: "ci", full: "cursedimages" },
  { nick: "dm", full: "dankmemes" },
  { nick: "efc", full: "extrafabulouscomics" },
  { nick: "gb", full: "gentlemanboners" },
  { nick: "h", full: "hmmm" },
  { nick: "hg", full: "hmmmgifs" },
  { nick: "hu", full: "holup" },
  { nick: "l20", full: "level20" },
  { nick: "lb", full: "ladyboners" },
  { nick: "ph", full: "programmerhumor" },
  { nick: "sfp", full: "shittyfoodporn" },
  { nick: "sg", full: "suddenlygay" },
  { nick: "sp", full: "starterpacks" },
  { nick: "tdnw", full: "thanosdidnothingwrong" },
  { nick: "tihi", full: "tihi" },
];
